# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-24 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('UNDER_REVIEW', 'Under Review'), ('DECLINED', 'Declined'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=12),
        ),
    ]
