# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20201224_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('NEW_FEATURE', 'New feature')], default='BUG', max_length=11),
        ),
    ]
