# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-21 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(default='', max_length=150),
        ),
    ]
