# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201110_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tag',
        ),
        migrations.AddField(
            model_name='ticket',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
