# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-23 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('UNDER_REVIEW', 'Under Review'), ('DECLINED', 'Declined'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=12),
        ),
    ]
